CREATE TABLE superhero(
	id SERIAL PRIMARY KEY,
	name VARCHAR (50) UNIQUE NOT NULL,
	alias VARCHAR (50) NOT NULL,
	origin VARCHAR (50) NOT NULL
);

CREATE TABLE assistant(
	id SERIAL PRIMARY KEY,
	name VARCHAR (50) UNIQUE NOT NULL
);

CREATE TABLE power(
	id SERIAL PRIMARY KEY,
	name VARCHAR (50) NOT NULL,
	description VARCHAR (50) NOT NULL
)
