CREATE TABLE superheroes(
	id SERIAL PRIMARY KEY,
	name VARCHAR (50) UNIQUE NOT NULL,
	alias VARCHAR (50) NOT NULL,
	origin VARCHAR (50) NOT NULL
);

CREATE TABLE assistants(
	id SERIAL PRIMARY KEY,
	name VARCHAR (50) UNIQUE NOT NULL
);

CREATE TABLE powers(
	id SERIAL PRIMARY KEY,
	name VARCHAR (50) NOT NULL,
	description VARCHAR (50) NOT NULL
)
